### ISSUE TITLE
unable to correct CUDA vs. JAX version mismatch

### ISSUE THREAD

**Issue by SJTUGuofei** [MIT-REALM/gcbfplus#1]
CUDA backend failed to initialize: Found cuDNN version 8600, but JAX was built against version 8906, which is newer. The copy of cuDNN that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

how can I deal with this issue?

**Comment by syzhang092218-source** [comment]
I guess you might want to update your CUDA and cuDNN versions.
