### ISSUE TITLE
Incompatible types in JAX

### ISSUE THREAD

**Issue by EdmundNegan** [MIT-REALM/gcbfplus#5]
Tracking run with wandb version 0.17.9
wandb: Run data is saved locally in ./logs/DoubleIntegrator/gcbf+/seed0_20240913182400\wandb\run-20240913_182409-dal1joh1
wandb: Run wandb offline to turn off syncing.
wandb: Syncing run gcbf+_DoubleIntegrator_20240913182400
wandb:  View project at https://wandb.ai/edmundgnan-ucl/gcbf-jax
wandb:  View run at https://wandb.ai/edmundgnan-ucl/gcbf-jax/runs/dal1joh1
step:   0, time:    14s, reward:  -15.6292, min/max reward:  -21.52/ -13.27, cost:  10.1328, unsafe_frac:   0.97, finish:   0.26
  0%|   

gcbfplus/lib/python3.10/site-packages/jax/_src/ops/scatter.py:92: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from dtype=int32 to dtype=bool with jax_numpy_dtype_promotion='standard'. In future JAX releases this will result in an error.
  warnings.warn(
  
  
  tried to run the code and got this error message about incompatible types in JAX. Do I need to change the version of JAX?

**Comment by syzhang092218-source** [comment]
I guess this is OK because it is a warning. If there is an error, try to use the Jax version 0.4.26.
